// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.hendisantika.springbootprotobufexample.proto;

public final class OuterPersonProto {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PersonProto_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PersonProto_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PersonProto_PhoneNumber_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PersonProto_PhoneNumber_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014Person.proto\"\303\001\n\013PersonProto\022\021\n\tfirstN" +
                        "ame\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\022\024\n\014emailAddr" +
                        "ess\030\003 \001(\t\022\023\n\013homeAddress\030\004 \001(\t\022.\n\014phoneN" +
                        "umbers\030\005 \003(\0132\030.PersonProto.PhoneNumber\0324" +
                        "\n\013PhoneNumber\022\020\n\010areaCode\030\001 \001(\005\022\023\n\013phone" +
                        "Number\030\002 \001(\005BF\n0com.hendisantika.springb" +
                        "ootprotobufexample.protoB\020OuterPersonPro" +
                        "toP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_PersonProto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_PersonProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PersonProto_descriptor,
                new java.lang.String[]{"FirstName", "LastName", "EmailAddress", "HomeAddress", "PhoneNumbers",});
        internal_static_PersonProto_PhoneNumber_descriptor =
                internal_static_PersonProto_descriptor.getNestedTypes().get(0);
        internal_static_PersonProto_PhoneNumber_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PersonProto_PhoneNumber_descriptor,
                new java.lang.String[]{"AreaCode", "PhoneNumber",});
    }

    private OuterPersonProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
